version: '2'
services:
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret 
        ports:
            - '3320:3306'
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        links:
            - mariadb
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
            - ./nginx/config/:/etc/nginx/conf.d
